name: Test

on:
  push:
    branches: [ master ]
    
jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Print tool_cache path
        run: |
          echo ${{ runner.tool_cache }}
          ls -la ${{ runner.tool_cache }}
          
      - name: Print Python directory structure
        run: |
          ls -la ${{ runner.tool_cache }}/Python
          ls -la ${{ runner.tool_cache }}/Python/3.7.8
          ls -la ${{ runner.tool_cache }}/Python/3.7.8/x64
          ls -la ${{ runner.tool_cache }}/Python/3.7.8/x64/Scripts
          
  windows:
    runs-on: windows-2016
    steps:
      - name: Print tool_cache path
        shell: bash
        run: |
          echo ${{ runner.tool_cache }}
          ls -la ${{ runner.tool_cache }}
          
      - name: Print Python directory structure
        shell: bash
        run: |
          ls -la ${{ runner.tool_cache }}/Python
          ls -la ${{ runner.tool_cache }}/Python/3.7.8
          ls -la ${{ runner.tool_cache }}/Python/3.7.8/x64
          ls -la ${{ runner.tool_cache }}/Python/3.7.8/x64/Scripts
    

